### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ram111222** [CedarBlocks/Simple-Discord-Bot-Website#6]
Hello my name is Ryan I recently forked your website and started it up on repl.it and found that their is no .html I'm not sure if this is intentional but it has renderd this git useless and hard to fix due to the complexity of this
Please fix this when u can

Ryan maicus / discord bot dev

**Comment by CedarBlocks** [comment]
The way this website works it does not use HTML files it uses [EJS](https://ejs.co) template engine and a JavaScript framework. So in order to use this website, you should have a basic understanding of [Node.js](https://nodejs.org/en/) and [EJS](https://ejs.co)

Sorry, I should make a tutorial on how to set it up.

**Comment by CedarBlocks** [comment]
Here it is running on repl.it https://replit.com/@JLDENSMORE/Simple-Discord-Bot-Website?v=1

**Comment by ram111222** [comment]
Well this will not work for me since I do not have a understanding of ejs but future ref you need to post that somewhere. You have a great day.

Ryan maicus/ discord bot developer
